title: Jean C. Flanagan
tagline: science education specialist and writer
author:
  name: Jean C. Flanagan
  email: jeancflanagan@gmail.com
url: http://jeancflanagan.com

pygments: true
layouts: ./_layouts
plugins: ./_plugins

permalink: /:year/:title
markdown: kramdown